
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/apollo?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: apollo
    password: apollo
    driver-class-name: com.mysql.cj.jdbc.Driver
  

###############################################
########### APOLLO PROPERTIES ###############
###############################################

