server:
  servlet:
    context-path: /apollo

spring:
  application:
    name: Apollo
  profiles:
    active: dev
  #jackson:
    #default-property-inclusion: NON_NULL
    #serialization:
      #write-dates-as-timestamps: true
  messages:
    basename: i18n/common, i18n/apollo
    encoding: UTF-8
    use-code-as-default-message: true
  jpa:
    properties:
      hibernate:
       dialect: org.hibernate.dialect.MariaDB53Dialect
       #current_session_context_class: thread
       hbm2ddl.auto: create-drop
       #format_sql: false
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

###############################################
############# APOLLO PROPERTIES #############
###############################################

apollo:
  dateformat: dd/MM/yyyy
cron:
  expression: 0 0 12 * * ?
  
  
  
  